# SPDX-License-Identifier: (GPL-2.0 OR BSD-2-Clause)

XDP_TARGETS  := xdp_prog_kern
USER_TARGETS := user_program
#DEPS = eml_net.h

LIBBPF_DIR = ../libbpf/src/
COMMON_DIR = ../common

COPY_LOADER := xdp_loader
COPY_STATS  := xdp_stats

#EXTRA_DEPS += eml_net.h

#CC := gcc
#CFLAGS += -lm
include $(COMMON_DIR)/common.mk
